server:
  port: 8080

spring:

  data:
    jpa:
      repositories:
        bootstrap-mode: default

#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

  application:
    name: spring-security

  jackson:
    serialization:
      write-dates-as-timestamps: 'false'
      write-date-timestamps-as-nanoseconds: 'true'

  messages:
    basename: messages/messages

#  security:
#    user:
#      name: grayroom
#      password: secret

logging:
  level:
    guru:
      sfg:
        brewery: debug
    org:
      springframework:
        security: debug
#      hibernate:
#        type:
#          descriptor:
#            sql: trace
